### PR TITLE
Rewrite test files from MonoidalCategories

### PR DESCRIPTION
**Pull request by TKuh**
See https://github.com/homalg-project/CategoryConstructor/pull/32

### CODE REVIEW

**Comment by TKuh** [comment]
So, without the PRs in MonoidalCategories and CategoryConstructor I get:

```gap
gap> ListInstalledOperationsOfCategory( SkeletalFinSets );
[ "AstrictionToCoimage", "AstrictionToCoimageWithGivenCoimage", "CanonicalIdentificationFromCoimageToImageObject",
  "CanonicalIdentificationFromImageObjectToCoimage", "CartesianAssociatorLeftToRight", 
  "CartesianAssociatorLeftToRightWithGivenDirectProducts", "CartesianAssociatorRightToLeft", 
  "CartesianAssociatorRightToLeftWithGivenDirectProducts", "CartesianBraiding", "CartesianBraidingInverse", 
  "CartesianBraidingInverseWithGivenDirectProducts", "CartesianBraidingWithGivenDirectProducts", 
  "CartesianCoevaluationMorphism", "CartesianCoevaluationMorphismWithGivenRange", "CartesianDualOnMorphisms", 
  "CartesianDualOnMorphismsWithGivenCartesianDuals", "CartesianDualOnObjects", 
  "CartesianEvaluationForCartesianDual", "CartesianEvaluationForCartesianDualWithGivenDirectProduct", 
  "CartesianEvaluationMorphism", "CartesianEvaluationMorphismWithGivenSource", "CartesianLambdaElimination", 
  "CartesianLambdaIntroduction", "CartesianLeftUnitor", "CartesianLeftUnitorInverse", 
  "CartesianLeftUnitorInverseWithGivenDirectProduct", "CartesianLeftUnitorWithGivenDirectProduct", 
  "CartesianPostComposeMorphism", "CartesianPostComposeMorphismWithGivenObjects", "CartesianPreComposeMorphism", 
  "CartesianPreComposeMorphismWithGivenObjects", "CartesianRightUnitor", "CartesianRightUnitorInverse", 
  "CartesianRightUnitorInverseWithGivenDirectProduct", "CartesianRightUnitorWithGivenDirectProduct", 
  "CartesianSquareOfSubobjectClassifier", "ClassifyingMorphismOfSubobject", 
  "ClassifyingMorphismOfSubobjectWithGivenSubobjectClassifier", "CoastrictionToImage", 
  "CoastrictionToImageWithGivenImageObject", "CocartesianAssociatorLeftToRight", 
  "CocartesianAssociatorLeftToRightWithGivenCoproducts", "CocartesianAssociatorRightToLeft", 
  "CocartesianAssociatorRightToLeftWithGivenCoproducts", "CocartesianLeftUnitor", "CocartesianLeftUnitorInverse", 
  "CocartesianLeftUnitorInverseWithGivenCoproduct", "CocartesianLeftUnitorWithGivenCoproduct", 
  "CocartesianRightUnitor", "CocartesianRightUnitorInverse", "CocartesianRightUnitorInverseWithGivenCoproduct", 
  "CocartesianRightUnitorWithGivenCoproduct", "Coequalizer", "CoequalizerFunctorial", 
  "CoequalizerFunctorialWithGivenCoequalizers", "Coimage", "CoimageProjection", 
  "CoimageProjectionWithGivenCoimage", "Colift", "ColiftAlongEpimorphism", "ColiftOrFail", "Coproduct", 
  "CoproductFunctorial", "CoproductFunctorialWithGivenCoproducts", "CoproductOnMorphisms", 
  "CoproductOnMorphismsWithGivenCoproducts", "DirectProduct", "DirectProductCartesianDualityCompatibilityMorphism"
    , "DirectProductCartesianDualityCompatibilityMorphismWithGivenObjects", 
  "DirectProductExponentialCompatibilityMorphism", "DirectProductExponentialCompatibilityMorphismWithGivenObjects"
    , "DirectProductFunctorial", "DirectProductFunctorialWithGivenDirectProducts", "DirectProductOnMorphisms", 
  "DirectProductOnMorphismsWithGivenDirectProducts", "DirectProductToExponentialAdjunctionMap", 
  "DistinguishedObjectOfHomomorphismStructure", "EmbeddingOfEqualizer", "EmbeddingOfEqualizerWithGivenEqualizer", 
  "EmbeddingOfIntersectionSubobject", "EmbeddingOfIntersectionSubobjectWithGivenIntersection", 
  "EmbeddingOfPseudoComplementSubobject", "EmbeddingOfPseudoComplementSubobjectWithGivenPseudoComplement", 
  "EmbeddingOfRelativePseudoComplementSuboject", "EmbeddingOfRelativePseudoComplementSubojectWithGivenImplication"
    , "EmbeddingOfUnionSubobject", "EmbeddingOfUnionSubobjectWithGivenUnion", 
  "EpimorphismFromSomeProjectiveObject", "EpimorphismFromSomeProjectiveObjectWithGivenSomeProjectiveObject", 
  "Equalizer", "EqualizerFunctorial", "EqualizerFunctorialWithGivenEqualizers", "ExponentialOnMorphisms", 
  "ExponentialOnMorphismsWithGivenExponentials", "ExponentialOnObjects", "ExponentialToDirectProductAdjunctionMap"
    , "FiberProduct", "FiberProductFunctorial", "FiberProductFunctorialWithGivenFiberProducts", 
  "HomomorphismStructureOnMorphisms", "HomomorphismStructureOnMorphismsWithGivenObjects", 
  "HomomorphismStructureOnObjects", "IdentityMorphism", "ImageEmbedding", "ImageEmbeddingWithGivenImageObject", 
  "ImageObject", "InitialObject", "InitialObjectFunctorial", "InitialObjectFunctorialWithGivenInitialObjects", 
  "InjectionOfCofactorOfCoproduct", "InjectionOfCofactorOfCoproductWithGivenCoproduct", 
  "InjectionOfCofactorOfPushout", "InjectionOfCofactorOfPushoutWithGivenPushout", "InjectiveColift", 
  "InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructure", 
  "InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructureWithGivenObjects", 
  "InterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism", "IntersectionSubobject", 
  "InverseForMorphisms", "IsAutomorphism", "IsCodominating", "IsColiftable", "IsColiftableAlongEpimorphism", 
  "IsCongruentForMorphisms", "IsDominating", "IsEndomorphism", "IsEpimorphism", "IsEqualAsFactorobjects", 
  "IsEqualAsSubobjects", "IsEqualForMorphisms", "IsEqualForMorphismsOnMor", "IsEqualForObjects", 
  "IsHomSetInhabited", "IsIdempotent", "IsIdenticalToIdentityMorphism", "IsInitial", "IsInjective", 
  "IsIsomorphism", "IsLiftable", "IsLiftableAlongMonomorphism", "IsMonomorphism", "IsOne", "IsProjective", 
  "IsSplitEpimorphism", "IsSplitMonomorphism", "IsTerminal", "IsWellDefinedForMorphisms", 
  "IsWellDefinedForObjects", "IsomorphismFromCartesianDualToExponential", 
  "IsomorphismFromCoequalizerOfCoproductDiagramToPushout", 
  "IsomorphismFromEqualizerOfDirectProductDiagramToFiberProduct", "IsomorphismFromExponentialToCartesianDual", 
  "IsomorphismFromExponentialToObject", "IsomorphismFromExponentialToObjectWithGivenExponential", 
  "IsomorphismFromFiberProductToEqualizerOfDirectProductDiagram", "IsomorphismFromObjectToExponential", 
  "IsomorphismFromObjectToExponentialWithGivenExponential", 
  "IsomorphismFromPushoutToCoequalizerOfCoproductDiagram", "Lift", "LiftAlongMonomorphism", "LiftOrFail", 
  "MonomorphismIntoSomeInjectiveObject", "MonomorphismIntoSomeInjectiveObjectWithGivenSomeInjectiveObject", 
  "MorphismConstructor", "MorphismDatum", "MorphismFromDirectProductToExponential", 
  "MorphismFromDirectProductToExponentialWithGivenObjects", "MorphismFromEqualizerToSink", 
  "MorphismFromEqualizerToSinkWithGivenEqualizer", "MorphismFromFiberProductToSink", 
  "MorphismFromFiberProductToSinkWithGivenFiberProduct", "MorphismFromSourceToCoequalizer", 
  "MorphismFromSourceToCoequalizerWithGivenCoequalizer", "MorphismFromSourceToPushout", 
  "MorphismFromSourceToPushoutWithGivenPushout", "MorphismToCartesianBidual", 
  "MorphismToCartesianBidualWithGivenCartesianBidual", "ObjectConstructor", "ObjectDatum", "PostCompose", 
  "PreCompose", "ProjectionInFactorOfDirectProduct", "ProjectionInFactorOfDirectProductWithGivenDirectProduct", 
  "ProjectionInFactorOfFiberProduct", "ProjectionInFactorOfFiberProductWithGivenFiberProduct", 
  "ProjectionOntoCoequalizer", "ProjectionOntoCoequalizerWithGivenCoequalizer", "ProjectiveLift", 
  "PseudoComplementSubobject", "Pushout", "PushoutFunctorial", "PushoutFunctorialWithGivenPushouts", 
  "RelativePseudoComplementSuboject", "SomeInjectiveObject", "SomeProjectiveObject", "SubobjectClassifier", 
  "SubobjectOfClassifyingMorphism", "TerminalObject", "TerminalObjectFunctorial", 
  "TerminalObjectFunctorialWithGivenTerminalObjects", "TruthMorphismOfAnd", "TruthMorphismOfAndWithGivenObjects", 
  "TruthMorphismOfFalse", "TruthMorphismOfFalseWithGivenObjects", "TruthMorphismOfImplies", 
  "TruthMorphismOfImpliesWithGivenObjects", "TruthMorphismOfNot", "TruthMorphismOfNotWithGivenObjects", 
  "TruthMorphismOfOr", "TruthMorphismOfOrWithGivenObjects", "TruthMorphismOfTrue", 
  "TruthMorphismOfTrueWithGivenObjects", "UnionSubobject", "UniversalMorphismFromCoequalizer", 
  "UniversalMorphismFromCoequalizerWithGivenCoequalizer", "UniversalMorphismFromCoproduct", 
  "UniversalMorphismFromCoproductWithGivenCoproduct", "UniversalMorphismFromImage", 
  "UniversalMorphismFromImageWithGivenImageObject", "UniversalMorphismFromInitialObject", 
  "UniversalMorphismFromInitialObjectWithGivenInitialObject", "UniversalMorphismFromPushout", 
  "UniversalMorphismFromPushoutWithGivenPushout", "UniversalMorphismIntoCoimage", 
  "UniversalMorphismIntoCoimageWithGivenCoimage", "UniversalMorphismIntoDirectProduct", 
  "UniversalMorphismIntoDirectProductWithGivenDirectProduct", "UniversalMorphismIntoEqualizer", 
  "UniversalMorphismIntoEqualizerWithGivenEqualizer", "UniversalMorphismIntoFiberProduct", 
  "UniversalMorphismIntoFiberProductWithGivenFiberProduct", "UniversalMorphismIntoTerminalObject", 
  "UniversalMorphismIntoTerminalObjectWithGivenTerminalObject", "UniversalPropertyOfCartesianDual" ]
```

with both PRs I get:

```gap
[ "AstrictionToCoimage", "AstrictionToCoimageWithGivenCoimage", "CanonicalIdentificationFromCoimageToImageObject",
  "CanonicalIdentificationFromImageObjectToCoimage", "CartesianAssociatorLeftToRight", 
  "CartesianAssociatorLeftToRightWithGivenDirectProducts", "CartesianAssociatorRightToLeft", 
  "CartesianAssociatorRightToLeftWithGivenDirectProducts", "CartesianBraiding", "CartesianBraidingInverse", 
  "CartesianBraidingInverseWithGivenDirectProducts", "CartesianBraidingWithGivenDirectProducts", 
  "CartesianCoevaluationMorphism", "CartesianCoevaluationMorphismWithGivenRange", "CartesianDualOnMorphisms", 
  "CartesianDualOnMorphismsWithGivenCartesianDuals", "CartesianDualOnObjects", 
  "CartesianEvaluationForCartesianDual", "CartesianEvaluationForCartesianDualWithGivenDirectProduct", 
  "CartesianEvaluationMorphism", "CartesianEvaluationMorphismWithGivenSource", "CartesianLambdaElimination", 
  "CartesianLambdaIntroduction", "CartesianLeftUnitor", "CartesianLeftUnitorInverse", 
  "CartesianLeftUnitorInverseWithGivenDirectProduct", "CartesianLeftUnitorWithGivenDirectProduct", 
  "CartesianPostComposeMorphism", "CartesianPostComposeMorphismWithGivenObjects", "CartesianPreComposeMorphism", 
  "CartesianPreComposeMorphismWithGivenObjects", "CartesianRightUnitor", "CartesianRightUnitorInverse", 
  "CartesianRightUnitorInverseWithGivenDirectProduct", "CartesianRightUnitorWithGivenDirectProduct", 
  "CartesianSquareOfSubobjectClassifier", "ClassifyingMorphismOfSubobject", 
  "ClassifyingMorphismOfSubobjectWithGivenSubobjectClassifier", "CoastrictionToImage", 
  "CoastrictionToImageWithGivenImageObject", "CocartesianAssociatorLeftToRight", 
  "CocartesianAssociatorLeftToRightWithGivenCoproducts", "CocartesianAssociatorRightToLeft", 
  "CocartesianAssociatorRightToLeftWithGivenCoproducts", "CocartesianLeftUnitor", "CocartesianLeftUnitorInverse", 
  "CocartesianLeftUnitorInverseWithGivenCoproduct", "CocartesianLeftUnitorWithGivenCoproduct", 
  "CocartesianRightUnitor", "CocartesianRightUnitorInverse", "CocartesianRightUnitorInverseWithGivenCoproduct", 
  "CocartesianRightUnitorWithGivenCoproduct", "Coequalizer", "CoequalizerFunctorial", 
  "CoequalizerFunctorialWithGivenCoequalizers", "Coimage", "CoimageProjection", 
  "CoimageProjectionWithGivenCoimage", "Colift", "ColiftAlongEpimorphism", "ColiftOrFail", "Coproduct", 
  "CoproductFunctorial", "CoproductFunctorialWithGivenCoproducts", "CoproductOnMorphisms", 
  "CoproductOnMorphismsWithGivenCoproducts", "DirectProduct", "DirectProductCartesianDualityCompatibilityMorphism"
    , "DirectProductCartesianDualityCompatibilityMorphismWithGivenObjects", 
  "DirectProductExponentialCompatibilityMorphism", "DirectProductExponentialCompatibilityMorphismWithGivenObjects"
    , "DirectProductFunctorial", "DirectProductFunctorialWithGivenDirectProducts", "DirectProductOnMorphisms", 
  "DirectProductOnMorphismsWithGivenDirectProducts", "DirectProductToExponentialAdjunctionMap", 
  "DistinguishedObjectOfHomomorphismStructure", "EmbeddingOfEqualizer", "EmbeddingOfEqualizerWithGivenEqualizer", 
  "EmbeddingOfIntersectionSubobject", "EmbeddingOfIntersectionSubobjectWithGivenIntersection", 
  "EmbeddingOfPseudoComplementSubobject", "EmbeddingOfPseudoComplementSubobjectWithGivenPseudoComplement", 
  "EmbeddingOfRelativePseudoComplementSuboject", "EmbeddingOfRelativePseudoComplementSubojectWithGivenImplication"
    , "EmbeddingOfUnionSubobject", "EmbeddingOfUnionSubobjectWithGivenUnion", 
  "EpimorphismFromSomeProjectiveObject", "EpimorphismFromSomeProjectiveObjectWithGivenSomeProjectiveObject", 
  "Equalizer", "EqualizerFunctorial", "EqualizerFunctorialWithGivenEqualizers", "ExponentialOnMorphisms", 
  "ExponentialOnMorphismsWithGivenExponentials", "ExponentialOnObjects", "ExponentialToDirectProductAdjunctionMap"
    , "FiberProduct", "FiberProductFunctorial", "FiberProductFunctorialWithGivenFiberProducts", 
  "HomomorphismStructureOnMorphisms", "HomomorphismStructureOnMorphismsWithGivenObjects", 
  "HomomorphismStructureOnObjects", "IdentityMorphism", "ImageEmbedding", "ImageEmbeddingWithGivenImageObject", 
  "ImageObject", "InitialObject", "InitialObjectFunctorial", "InitialObjectFunctorialWithGivenInitialObjects", 
  "InjectionOfCofactorOfCoproduct", "InjectionOfCofactorOfCoproductWithGivenCoproduct", 
  "InjectionOfCofactorOfPushout", "InjectionOfCofactorOfPushoutWithGivenPushout", "InjectiveColift", 
  "InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructure", 
  "InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructureWithGivenObjects", 
  "InterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism", "IntersectionSubobject", 
  "InverseForMorphisms", "IsAutomorphism", "IsCodominating", "IsColiftable", "IsColiftableAlongEpimorphism", 
  "IsCongruentForMorphisms", "IsDominating", "IsEndomorphism", "IsEpimorphism", "IsEqualAsFactorobjects", 
  "IsEqualAsSubobjects", "IsEqualForMorphisms", "IsEqualForMorphismsOnMor", "IsEqualForObjects", 
  "IsHomSetInhabited", "IsIdempotent", "IsIdenticalToIdentityMorphism", "IsInitial", "IsInjective", 
  "IsIsomorphism", "IsLiftable", "IsLiftableAlongMonomorphism", "IsMonomorphism", "IsOne", "IsProjective", 
  "IsSplitEpimorphism", "IsSplitMonomorphism", "IsTerminal", "IsWellDefinedForMorphisms", 
  "IsWellDefinedForObjects", "IsomorphismFromCartesianDualToExponential", 
  "IsomorphismFromCoequalizerOfCoproductDiagramToPushout", 
  "IsomorphismFromEqualizerOfDirectProductDiagramToFiberProduct", "IsomorphismFromExponentialToCartesianDual", 
  "IsomorphismFromExponentialToObject", "IsomorphismFromExponentialToObjectWithGivenExponential", 
  "IsomorphismFromFiberProductToEqualizerOfDirectProductDiagram", "IsomorphismFromObjectToExponential", 
  "IsomorphismFromObjectToExponentialWithGivenExponential", 
  "IsomorphismFromPushoutToCoequalizerOfCoproductDiagram", "Lift", "LiftAlongMonomorphism", "LiftOrFail", 
  "MonomorphismIntoSomeInjectiveObject", "MonomorphismIntoSomeInjectiveObjectWithGivenSomeInjectiveObject", 
  "MorphismConstructor", "MorphismDatum", "MorphismFromDirectProductToExponential", 
  "MorphismFromDirectProductToExponentialWithGivenObjects", "MorphismFromEqualizerToSink", 
  "MorphismFromEqualizerToSinkWithGivenEqualizer", "MorphismFromFiberProductToSink", 
  "MorphismFromFiberProductToSinkWithGivenFiberProduct", "MorphismFromSourceToCoequalizer", 
  "MorphismFromSourceToCoequalizerWithGivenCoequalizer", "MorphismFromSourceToPushout", 
  "MorphismFromSourceToPushoutWithGivenPushout", "MorphismToCartesianBidual", 
  "MorphismToCartesianBidualWithGivenCartesianBidual", "ObjectConstructor", "ObjectDatum", "PostCompose", 
  "PostInverse", "PreCompose", "PreInverse", "ProjectionInFactorOfDirectProduct", 
  "ProjectionInFactorOfDirectProductWithGivenDirectProduct", "ProjectionInFactorOfFiberProduct", 
  "ProjectionInFactorOfFiberProductWithGivenFiberProduct", "ProjectionOntoCoequalizer", 
  "ProjectionOntoCoequalizerWithGivenCoequalizer", "ProjectiveLift", "PseudoComplementSubobject", "Pushout", 
  "PushoutFunctorial", "PushoutFunctorialWithGivenPushouts", "RelativePseudoComplementSuboject", 
  "SomeInjectiveObject", "SomeProjectiveObject", "SubobjectClassifier", "SubobjectOfClassifyingMorphism", 
  "TerminalObject", "TerminalObjectFunctorial", "TerminalObjectFunctorialWithGivenTerminalObjects", 
  "TruthMorphismOfAnd", "TruthMorphismOfAndWithGivenObjects", "TruthMorphismOfFalse", 
  "TruthMorphismOfFalseWithGivenObjects", "TruthMorphismOfImplies", "TruthMorphismOfImpliesWithGivenObjects", 
  "TruthMorphismOfNot", "TruthMorphismOfNotWithGivenObjects", "TruthMorphismOfOr", 
  "TruthMorphismOfOrWithGivenObjects", "TruthMorphismOfTrue", "TruthMorphismOfTrueWithGivenObjects", 
  "UnionSubobject", "UniversalMorphismFromCoequalizer", "UniversalMorphismFromCoequalizerWithGivenCoequalizer", 
  "UniversalMorphismFromCoproduct", "UniversalMorphismFromCoproductWithGivenCoproduct", 
  "UniversalMorphismFromImage", "UniversalMorphismFromImageWithGivenImageObject", 
  "UniversalMorphismFromInitialObject", "UniversalMorphismFromInitialObjectWithGivenInitialObject", 
  "UniversalMorphismFromPushout", "UniversalMorphismFromPushoutWithGivenPushout", "UniversalMorphismIntoCoimage", 
  "UniversalMorphismIntoCoimageWithGivenCoimage", "UniversalMorphismIntoDirectProduct", 
  "UniversalMorphismIntoDirectProductWithGivenDirectProduct", "UniversalMorphismIntoEqualizer", 
  "UniversalMorphismIntoEqualizerWithGivenEqualizer", "UniversalMorphismIntoFiberProduct", 
  "UniversalMorphismIntoFiberProductWithGivenFiberProduct", "UniversalMorphismIntoTerminalObject", 
  "UniversalMorphismIntoTerminalObjectWithGivenTerminalObject", "UniversalPropertyOfCartesianDual" ]
```
Their difference:

```gap
gap> Difference( new, old );
[ "PostInverse", "PreInverse" ]
```
Can someone reproduce that?

**Comment by zickgraf** [comment]
Ah, I think this due to the version bumps: Toposes only loads CategoryConstructor if all versions are bumped. And CategoryConstructor adds some CAP operations, so this influences the number of installed operations.

**Comment by TKuh** [comment]
Oh, I see, thank you!

**Comment by zickgraf** [comment]
Sadly, suggested dependencies are a not-so-uncommon source of unexpected result :/

**Pull request merged**
