### PR TITLE
derived homomorphism structure from closed cartesian structure

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@zickgraf: In the tests of Locales the compiler is complaining about an unset `RangeCategoryOfHomomorphismStructure`, although I assign it in `FunctionCalledBeforeInstallation`.

**Comment by zickgraf** [comment]
There was a small bug in the compiler, fixed by https://github.com/homalg-project/CAP_project/pull/781.

**Comment by mohamed-barakat** [comment]
> There was a small bug in the compiler, fixed by [homalg-project/CAP_project#781](https://github.com/homalg-project/CAP_project/pull/781).

Wonderful, thank you very much for the fix.

**Comment by mohamed-barakat** [comment]
Now, `FinSets` and by https://github.com/homalg-project/FinSetsForCAP/pull/73 will have a homomorphism structure derived from the closed cartesian structure.

**Pull request merged**
