### PR TITLE
Translation of distributive (co)cartesian categories and their tests

### PR DESCRIPTION
**Pull request by TKuh**
Regenerated Toposes

* from MonoidalCategories v2022.04-01
* using CategoryConstructor v2022.04-06

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I think the test file `tst/Opposite.tst` needs to be updated.

**Comment by TKuh** [comment]
It worked fine on my laptop, I don't know what's causing this.

**Comment by mohamed-barakat** [comment]
> It worked fine on my laptop, I don't know what's causing this.

I think because `CategoryConstructor` is not loaded.

**Comment by mohamed-barakat** [comment]
Could you set back the suggested dependency of `CategoryConstructor` temporarily back to `2022.03-01`

**Pull request merged**
