### PR TITLE
Bug in the derivation of CoexponentialCoproductCompatibilityMorphism

### PR DESCRIPTION
**Pull request by TKuh**
A result of https://github.com/homalg-project/CAP_project/pull/835
And again unsure about the versioning (and the version of MonoidalCategories in the SuggestedPackages section).

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Could you please alter the commit message to

```
regenerated Toposes

* from MonoidalCategories v2022.01-09
* using CategoryConstructor v2022.02-08
```

**Comment by mohamed-barakat** [comment]
Why wasn't the file `AUTOGENERATED_FROM.md` updated by `CreateFilesForToposesPackage()`? Maybe you made changes manually?

**Comment by TKuh** [comment]
I somehow missed to add it to the commit, sorry. :/

**Comment by mohamed-barakat** [comment]
> I somehow missed to add it to the commit, sorry. :/

No problem :) Looks good now. Thank you very much. Will merge after the tests pass.

**Pull request merged**
