### PR TITLE
d&i InitialCategory

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by zickgraf** [comment]
I'm not in favor of using CAP's default equalities (see https://github.com/homalg-project/CAP_project/pull/621#issue-737797017), so I would suggest installing at least `IsEqualForObjects`, `IsEqualForMorphisms` and `IsCongruentForMorphisms`, with the implementations simply throwing an error. Furthermore I would suggest installing `PreCompose` and `IdentityMorphism` to show that this actually is a computable category.

**Comment by mohamed-barakat** [comment]
Just for your info and for further discussion: The motivation for the refactoring of TerminalCategory was this here

https://github.com/homalg-project/FunctorCategories/commit/fe14c9586f01feb10f34a5bebbaae0b882ea5718

**Comment by zickgraf** [comment]
> Just for your info and for further discussion: The motivation for the refactoring of TerminalCategory was this here
> 
> [homalg-project/FunctorCategories@fe14c95](https://github.com/homalg-project/FunctorCategories/commit/fe14c9586f01feb10f34a5bebbaae0b882ea5718)

Is this a reply to my comment above? If yes, I don't see the connection: I'm talking about the initial category not the terminal category. Or do you just want to point out your application of the initial category? In that case I understand that one does not need my suggestion for those things to work, but I think my suggestions still make sense.

**Comment by mohamed-barakat** [comment]
Yes, I agree with your suggestions. I just wanted to give you more context, to why I wanted `InitialCategory` in the first place :)

**Pull request merged**
